ATMChallengeOrigin/Models/Card.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ATMChallengeOrigin.Models
{
    public class Card
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [RegularExpression("^[0-9]{16}$")]
        public string CardNumber { get; set; }
        [Required]
        [RegularExpression("^[0-9]{4}$")]
        public string EncryptedPin { get; set; }
        public bool IsBlocked { get; set; }
        public double Balance { get; set; }
        public int CountError { get; set; }
        public DateTime ExpirationDate { get; set; }

    }
}

ATMChallengeOrigin/Models/Operation.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ATMChallengeOrigin.Models
{
    public class Operation
    {
        [Key]
        public int Id { get; set; }
        public int CardId { get; set; }
        
        [ForeignKey("CardId")]
        [ValidateNever]
        public Card Card { get; set; }

        public string Code { get; set; }
        public DateTime Time { get; set; }        
        public double? MoneyWithdrawn { get; set; }

    }
}

ATMChallengeOrigin/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ATMChallengeOrigin.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string ErrorMessage { get; set; }

        public void OnGet()
        {
            ErrorMessage = TempData["ErrorMessage"]?.ToString();
        }
        public IActionResult OnPostLogOut()
        {
            return RedirectToPage("/Index");
        }
    }

}

ATMChallengeOrigin/Pages/Index.cshtml.cs
using ATMChallengeOrigin.Data;
using ATMChallengeOrigin.Data.Repository.IRepository;
using ATMChallengeOrigin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ATMChallengeOrigin.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IUnitOfWork _unitOfWork;
        public Card Card { get; set; }

        public IndexModel(ILogger<IndexModel> logger, IUnitOfWork unitOfWork)
        {
            _logger = logger;
            _unitOfWork = unitOfWork;
        }

        public void OnGet()
        {

        }

        public IActionResult OnPost(string cardNumber)
        {
            if (cardNumber != null)
            {
                cardNumber = cardNumber.Replace("-", "");
            }
            Card cardSearched = _unitOfWork.Card.GetFirstOrDefault(x => x.CardNumber == cardNumber);

            if (cardSearched != null && !cardSearched.IsBlocked)
            {
                return RedirectToPage("cards/Index", new { id = cardSearched.Id });
            }
            if (cardSearched == null)
            {
                TempData["ErrorMessage"] = "ERROR. Tarjeta incorrecta.";
            }
            else { TempData["ErrorMessage"] = "ERROR. Tarjeta bloqueada. Dírigase a la sucursal más cercana para realizar el desbloqueo"; }
            return RedirectToPage("/Error");
        }

    }
}

ATMChallengeOrigin/Pages/Operations/Balance.cshtml.cs
using ATMChallengeOrigin.Data;
using ATMChallengeOrigin.Data.Repository.IRepository;
using ATMChallengeOrigin.Models;
using ATMChallengeOrigin.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ATMChallengeOrigin.Pages.Operations
{
    public class BalanceModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        [BindProperty]
        public Card Card { get; set; }


        public BalanceModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public void OnGet(int cardId)
        {
            Card = _unitOfWork.Card.Get(cardId);
            GenerateBalance();
        }

        public IActionResult OnPost()
        {
            return RedirectToPage("/Operations/Operation", new { cardId = Card.Id });
        }

        public IActionResult OnPostLogOut()
        {
            return RedirectToPage("/Index");
        }

        private void GenerateBalance()
        {
            var operation = new Operation
            {
                CardId = Card.Id,
                Time = DateTime.Now,
                Code = RandomCode.RandomString(8)
            };

            _unitOfWork.Operation.Add(operation);
            _unitOfWork.Save();
        }
    }
}

ATMChallengeOrigin/Pages/Operations/Operation.cshtml.cs
using ATMChallengeOrigin.Data.Repository.IRepository;
using ATMChallengeOrigin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ATMChallengeOrigin.Pages.Operations
{
    public class OperationModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        [BindProperty]
        public Card Card { get; set; }

        public OperationModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public void OnGet(int id)
        {
            Card = _unitOfWork.Card.Get(id);
        }

        public IActionResult OnPostBalance()
        {
            return RedirectToPage("../operations/Balance", new { cardId = Card.Id });
        }

        public IActionResult OnPostWithdrawal()
        {
            return RedirectToPage("../operations/Withdrawal", new { cardId = Card.Id });
        }

        public IActionResult OnPostLogOut()
        {
            return RedirectToPage("/Index");
        }
    }
}

ATMChallengeOrigin/Pages/Operations/OperationReport.cshtml.cs
using ATMChallengeOrigin.Data.Repository.IRepository;
using ATMChallengeOrigin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ATMChallengeOrigin.Pages.Operations
{
    public class OperationReportModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        [BindProperty]
        public Card Card { get; set; }
        public Operation Operation { get; set; }

        public OperationReportModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public void OnGet(string operationCode)
        {
            Operation = _unitOfWork.Operation.GetFirstOrDefault(x => x.Code == operationCode);
            Card = _unitOfWork.Card.Get(Operation.CardId);
           
        }
    }
}

ATMChallengeOrigin/Pages/Operations/Withdrawal.cshtml.cs
using System;
using ATMChallengeOrigin.Data.Repository.IRepository;
using ATMChallengeOrigin.Migrations;
using ATMChallengeOrigin.Models;
using ATMChallengeOrigin.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ATMChallengeOrigin.Pages
{
    public class WithdrawalModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        [BindProperty]
        public Card Card { get; set; }

        public WithdrawalModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public void OnGet(int cardId)
        {
            Card = _unitOfWork.Card.Get(cardId);
        }


        public IActionResult OnPostWithdraw(double mount)
        {
            Card = _unitOfWork.Card.Get(Card.Id);
            if (mount > Card.Balance)
            {
                TempData["ErrorMessage"] = "ERROR. El monto es superior al saldo disponible.";
                return RedirectToPage("/Error");
            }
            else
            {
                string operationCode = CreateRecord(mount); 
                Card.Balance -= mount;
                _unitOfWork.Card.Update(Card);
                _unitOfWork.Save();

                return Redirect($"/operations/OperationReport?operationCode={operationCode}");
            }
        }

        private string CreateRecord(double mount)
        {
            var operation = new Operation
            {
                CardId = Card.Id,
                Time = DateTime.Now,
                Code = RandomCode.RandomString(8),
                MoneyWithdrawn = mount
            };
            _unitOfWork.Operation.Add(operation);
            _unitOfWork.Save();

            return operation.Code; 
        }

    }
}

ATMChallengeOrigin/Pages/Cards/Index.cshtml
@page
@model Cards.IndexModel
@{
    ViewData["Title"] = "Ingresar PIN";
}


<div>
    <h1>Ingrese el PIN de la tarjeta</h1>

    <form method="post">

        <input type="password" id="pin" name="pin" class="form-control" readonly="readonly" />


        <div class="numeric-keypad mt-3">
            @for (int i = 1; i <= 9; i++)
            {
                <button type="button" class="btn btn-info" onclick="appendDigit(@i)">@i</button>
            }
            <button type="button" class="btn btn-info" onclick="appendDigit(0)">0</button>
        </div>

        <div class="form-group mt-3">
            <button type="submit" name="submit" class="btn btn-success">Aceptar</button>
            <button type="button" class="btn btn-danger ml-3" onclick="exit()">Salir</button>
            <button type="button" class="btn btn-primary ml-3" onclick="clearInput()">Limpiar</button>
        </div>
    </form>
</div>


<script>
    function appendDigit(digit) {
        var pin = document.getElementById("pin");
        if (pin.value.length < 5) {
            pin.value += digit;
        }
    }

    function clearInput() {
        document.getElementById("pin").value = "";
    }

    function exit() {

        window.location.href = "/";
    }
</script>

<partial name="_ValidationScriptsPartial" />

ATMChallengeOrigin/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Inicio";
}

<h1>Ingrese el número de su tarjeta</h1>

<form method="post">
    <div>
        <input type="text" id="cardNumber" name="cardNumber" class="form-control" readonly="readonly" />
    </div>

    <div>
        <div class="numeric-keypad mt-3">
            @for (int i = 1; i <= 9; i++)
            {
                <button type="button" class="btn btn-info" onclick="appendDigit(@i)">@i</button>
            }
            <button type="button" class="btn btn-info" onclick="appendDigit(0)">0</button>
        </div>
    </div>

    <div class="form-group mt-3">
        <button type="submit" name="submit" class="btn btn-success">Aceptar</button>
        <button type="button" class="btn btn-primary ml-3" onclick="clearInput()">Limpiar</button>
    </div>
</form>

<script>
    function appendDigit(digit) {
        var cardNumber = document.getElementById("cardNumber");
        cardNumber.value += digit;

        if (cardNumber.value.length === 4 || cardNumber.value.length === 9 || cardNumber.value.length === 14) {
            cardNumber.value += "-";
        }

        if (cardNumber.value.length >= 19) {
            cardNumber.value = cardNumber.value.substring(0, 19);
        }
    }

    function clearInput() {
        document.getElementById("cardNumber").value = "";
    }
</script>

ATMChallengeOrigin/Pages/Operations/Balance.cshtml
@page
@model ATMChallengeOrigin.Pages.Operations.BalanceModel
@{
    ViewData["Title"] = "Balance";
}

<style>

    .box-container {
        border: 1px solid #ccc; 
        padding: 20px; 
        box-shadow: 0 0 5px rgba(0, 0, 0, 0.2); 
    }
</style>

<div class="box-container">
    <h1>Balance</h1>

    @if (Model.Card != null)
    {
        <div>
            <p>Número de Tarjeta: @string.Join("-", Model.Card.CardNumber.Substring(0, 4), Model.Card.CardNumber.Substring(4, 4), Model.Card.CardNumber.Substring(8, 4), Model.Card.CardNumber.Substring(12, 4))</p>
            <p>Cantidad de saldo en la Cuenta: @Model.Card.Balance$</p>
            <p>Fecha de vencimiento: @Model.Card.ExpirationDate.ToString("dd/MM/yyyy")</p>
        </div>
    }

    <div>
        <a asp-page="/Operations/Operation" asp-route-id="@Model.Card.Id">Atrás</a>
        <a asp-page="/Index">Salir</a>
    </div>
</div>

ATMChallengeOrigin/Pages/Operations/Operation.cshtml
@page
@model ATMChallengeOrigin.Pages.Operations.OperationModel
@{
    <style>
        button {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            margin: 5px;
        }

        .btn-exit {
            background-color: #dc3545; 
        }

        button:hover {
            background-color: #0056b3; 
        }
    </style>


    <h1>Operaciones disponibles</h1>
    <form method="post">
        <input type="hidden" asp-for="Card.Id" />
        <input type="hidden" asp-for="Card.EncryptedPin" />
        <button type="submit" asp-page-handler="Balance" class="custom-button">Balance</button>
        <button type="submit" asp-page-handler="Withdrawal" class="custom-button">Retiro</button>
        <button type="submit" asp-page-handler="LogOut" class="custom-button btn-exit">Salir</button>

    </form>
}

ATMChallengeOrigin/Pages/Operations/OperationReport.cshtml
@page
@model ATMChallengeOrigin.Pages.Operations.OperationReportModel
@{
    ViewData["Title"] = "Reporte de Operación";
}

<style>
    /* Estilo para el contenedor del reporte de operación */
    .report-container {
        border: 1px solid #ccc; /* Borde con color gris claro */
        padding: 20px; /* Espaciado interno */
        box-shadow: 0 0 5px rgba(0, 0, 0, 0.2); /* Sombreado ligero */
    }
</style>

<div class="report-container">
    <h1>Reporte de Operación</h1>

    <div>
        <p>Número de Tarjeta: @Model.Card.CardNumber</p>
        <p>Fecha y Hora: @Model.Operation.Time</p>
        <p>Cantidad Retirada: @Model.Operation.MoneyWithdrawn $</p>
        <p>Balance actual de la Cuenta: @Model.Card.Balance $</p>
    </div>

    <div>
        <a asp-page="../Operations/Withdrawal" asp-route-cardId="@Model.Card.Id" class="btn btn-info">Atrás</a>
        <a asp-page="/Index" class="btn btn-danger">Salir</a>
    </div>
</div>

ATMChallengeOrigin/Pages/Operations/Withdrawal.cshtml
@page
@model ATMChallengeOrigin.Pages.WithdrawalModel
@{
    ViewData["Title"] = "Retiro";
}

<div>
    <h1>Página de Retiro</h1>

    <form method="post">
        <div>
            <input type="text" id="mount" name="mount" class="form-control" readonly="readonly" />
        </div>

        <div class="numeric-keypad mt-3">
            @for (int i = 1; i <= 9; i++)
            {
                <button type="button" class="btn btn-info" onclick="appendDigit(@i)">@i</button>
            }
            <button type="button" class="btn btn-info" onclick="appendDigit(0)">0</button>
            <button type="button" class="btn btn-primary ml-3" onclick="clearInput()">Limpiar</button>
        </div>

        <div class="form-group mt-3">
            <button type="submit" name="submit" asp-page-handler="Withdraw" class="btn btn-success">Aceptar</button>
            <button type="button" class="btn btn-danger ml-3" onclick="exit()">Salir</button>
        </div>
        <input type="hidden" name="Card.Id" value="@Model.Card.Id" />
    </form>
</div>

<script>
    function appendDigit(digit) {
        var mount = document.getElementById("mount");
        mount.value += digit;
    }

    function clearInput() {
        document.getElementById("mount").value = "";
    }

    function exit() {
        window.location.href = "/";
    }
</script>

ATMChallengeOrigin/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ATMChallengeOrigin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ATMChallengeOrigin.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ATMChallengeOrigin</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                     
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-muted">
        <div class="container">
            &copy; 2023 - ATMChallengeOrigin 
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>



    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ATMChallengeOrigin/Pages/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}